import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RefferGenix",
  description: "RefferGenix - The Bandu chapter app",
};

/**
 * RootLayout component is the root layout component for the application.
 * It wraps all the child components with the basic HTML structure.
 *
 * @param {Object} props - The properties passed to the component.
 * @param {ReactNode} props.children - The child components to be rendered.
 * @returns {JSX.Element} The RootLayout component.
 */
export default function RootLayout({ children }) {
  // Render the root layout with the basic HTML structure
  return (
    <html lang="en" >
      {/* Set the body class to the font class generated by Inter */}
      <body className={inter.className}>
        {/* Render the child components */}
        {children}
      </body>
    </html>
  );
}
